name: 'java-prepare-action'
description: 'Get build project and test'
inputs:
  javas-version:
    description: 'java version'
    required: true
  github-token:
    description: 'The GitHub token to upload the code coverage report'
    required: true
  GPR_USERNAME:
    description: ''
    required: true
  update-coverage-comment:
    description: 'Update the coverage comment'
    required: false
    default: true
  block-pull-request:
    description: 'block pull request for not exceeding the minimum coverage percentage'
    required: false
    default: false
  block-pull-request-min-coverage-global:
    description: 'minimum percentage required'
    required: false
    default: 40
  block-pull-request-min-coverage-file:
    description: 'minimum percentage required for file'
    required: false
    default: 50
  sonar_token:
    description: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.javas-version }}
        distribution: 'corretto'

    - name: variable
      run: echo ${{ runner.os }}
      shell: bash

    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=jhonatan-barreto-ueno_kyc-core
      shell: bash


    - name: Add coverages to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: |
          ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
        token: ${{ inputs.github-token }}
        min-coverage-overall: ${{inputs.block-pull-request-min-coverage-global}}
        min-coverage-changed-files: ${{inputs.block-pull-request-min-coverage-file}}
        title: Code coverage
        update-comment: ${{inputs.update-coverage-comment}}

    - name: Fail PR if overall coverage is low
      if: ${{ inputs.block-pull-request && steps.jacoco.outputs.coverage-overall < inputs.block-pull-request-min-coverage-global }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Overall coverage is less than 60%!')
      
        
