name: 'java-prepare-action'
description: 'Get build project and test'
inputs:
  javas-version:
    description: 'java version'
    required: true
  github-token:
    description: 'The GitHub token to upload the code coverage report'
    required: true
  update-coverage-comment:
    description: 'Update the coverage comment'
    required: false
    default: true
  block-pull-request:
    description: 'block pull request for not exceeding the minimum coverage percentage'
    required: false
    default: false
  block-pull-request-min-coverage-global:
    description: 'minimum percentage required'
    required: false
    default: 40
  block-pull-request-min-coverage-file:
    description: 'minimum percentage required for file'
    required: false
    default: 50
