name: 'java-prepare-action'
description: 'Get build project and test'
inputs:
  javas-version:
    description: 'java version'
    required: true
  github-token:
    description: 'The GitHub token to upload the code coverage report'
    required: true
  update-coverage-comment:
    description: 'Update the coverage comment'
    required: false
    default: true
  block-pull-request:
    description: 'block pull request for not exceeding the minimum coverage percentage'
    required: false
    default: false
  block-pull-request-min-coverage-global:
    description: 'minimum percentage required'
    required: false
    default: 40
  block-pull-request-min-coverage-file:
    description: 'minimum percentage required for file'
    required: false
    default: 50
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.javas-version }}
        distribution: 'corretto'

    - name: Set maven settings
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: '[
                        { "id": "spring-milestone", "url": "https://repo.spring.io/milestone/"},
                        { "id": "oss-sonatype", "url": "https://oss.sonatype.org/service/local/repositories/releases/content/"}
                      ]'
        plugin_repositories: '[{ "id": "spring-milestone", "url": "https://repo.spring.io/milestone/"}]'

    - name: Maven test
      shell: bash
      run: mvn clean test --no-transfer-progress

    - name: Add coverages to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: |
          ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
        token: ${{ inputs.github-token }}
        min-coverage-overall: ${{inputs.block-pull-request-min-coverage-global}}
        min-coverage-changed-files: ${{inputs.block-pull-request-min-coverage-file}}
        title: Code coverage
        update-comment: ${{inputs.update-coverage-comment}}
