name: main
on: [pull_request]

jobs:
  test_job:
    permissions: write-all
    runs-on: ubuntu-latest
    name: checks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if GITHUB_TOKEN is empty
        run: |
          if [[ -z "${{ secrets.GITHUB_TOKEN }}" ]]; then
            echo "GITHUB_TOKEN is empty"
            exit 1
          else
            echo "GITHUB_TOKEN is not empty"
          fi
        shell: bash
      - name: Executes java-prepare-action
        uses: ./ # Uses an action in the root directory
        id: fpa
        with:
          javas-version: '17'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          block-pull-request-min-coverage-global: 60
          block-pull-request: true